/* tslint:disable */
/* eslint-disable */
/**
 * Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { VenueListItemDto } from "./VenueListItemDto";
import {
  VenueListItemDtoFromJSON,
  VenueListItemDtoFromJSONTyped,
  VenueListItemDtoToJSON,
} from "./VenueListItemDto";

/**
 *
 * @export
 * @interface ListVenuesResponse
 */
export interface ListVenuesResponse {
  /**
   *
   * @type {Array<VenueListItemDto>}
   * @memberof ListVenuesResponse
   */
  venues?: Array<VenueListItemDto> | null;
}

/**
 * Check if a given object implements the ListVenuesResponse interface.
 */
export function instanceOfListVenuesResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ListVenuesResponseFromJSON(json: any): ListVenuesResponse {
  return ListVenuesResponseFromJSONTyped(json, false);
}

export function ListVenuesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListVenuesResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    venues: !exists(json, "venues")
      ? undefined
      : json["venues"] === null
        ? null
        : (json["venues"] as Array<any>).map(VenueListItemDtoFromJSON),
  };
}

export function ListVenuesResponseToJSON(
  value?: ListVenuesResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    venues:
      value.venues === undefined
        ? undefined
        : value.venues === null
          ? null
          : (value.venues as Array<any>).map(VenueListItemDtoToJSON),
  };
}
