/* tslint:disable */
/* eslint-disable */
/**
 * Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ListVenuesSortOrder = {
  Distance: "Distance",
  Name: "Name",
  StarsBeer: "StarsBeer",
  StarsAtmosphere: "StarsAtmosphere",
  StarsAmenities: "StarsAmenities",
  StarsValue: "StarsValue",
} as const;
export type ListVenuesSortOrder =
  (typeof ListVenuesSortOrder)[keyof typeof ListVenuesSortOrder];

export function ListVenuesSortOrderFromJSON(json: any): ListVenuesSortOrder {
  return ListVenuesSortOrderFromJSONTyped(json, false);
}

export function ListVenuesSortOrderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListVenuesSortOrder {
  return json as ListVenuesSortOrder;
}

export function ListVenuesSortOrderToJSON(
  value?: ListVenuesSortOrder | null,
): any {
  return value as any;
}
