/* tslint:disable */
/* eslint-disable */
/**
 * Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VenueDetailDto
 */
export interface VenueDetailDto {
  /**
   *
   * @type {number}
   * @memberof VenueDetailDto
   */
  venueId: number;
  /**
   *
   * @type {string}
   * @memberof VenueDetailDto
   */
  venueName: string;
  /**
   *
   * @type {string}
   * @memberof VenueDetailDto
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof VenueDetailDto
   */
  thumbnail: string;
  /**
   *
   * @type {string}
   * @memberof VenueDetailDto
   */
  excerpt: string;
  /**
   *
   * @type {Array<string>}
   * @memberof VenueDetailDto
   */
  tags: Array<string>;
  /**
   *
   * @type {string}
   * @memberof VenueDetailDto
   */
  address: string;
  /**
   *
   * @type {number}
   * @memberof VenueDetailDto
   */
  starsBeer: number;
  /**
   *
   * @type {number}
   * @memberof VenueDetailDto
   */
  starsAtmosphere: number;
  /**
   *
   * @type {number}
   * @memberof VenueDetailDto
   */
  starsAmenities: number;
  /**
   *
   * @type {number}
   * @memberof VenueDetailDto
   */
  starsValue: number;
  /**
   *
   * @type {string}
   * @memberof VenueDetailDto
   */
  phone?: string | null;
  /**
   *
   * @type {string}
   * @memberof VenueDetailDto
   */
  twitter?: string | null;
}

/**
 * Check if a given object implements the VenueDetailDto interface.
 */
export function instanceOfVenueDetailDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "venueId" in value;
  isInstance = isInstance && "venueName" in value;
  isInstance = isInstance && "url" in value;
  isInstance = isInstance && "thumbnail" in value;
  isInstance = isInstance && "excerpt" in value;
  isInstance = isInstance && "tags" in value;
  isInstance = isInstance && "address" in value;
  isInstance = isInstance && "starsBeer" in value;
  isInstance = isInstance && "starsAtmosphere" in value;
  isInstance = isInstance && "starsAmenities" in value;
  isInstance = isInstance && "starsValue" in value;

  return isInstance;
}

export function VenueDetailDtoFromJSON(json: any): VenueDetailDto {
  return VenueDetailDtoFromJSONTyped(json, false);
}

export function VenueDetailDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VenueDetailDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    venueId: json["venueId"],
    venueName: json["venueName"],
    url: json["url"],
    thumbnail: json["thumbnail"],
    excerpt: json["excerpt"],
    tags: json["tags"],
    address: json["address"],
    starsBeer: json["starsBeer"],
    starsAtmosphere: json["starsAtmosphere"],
    starsAmenities: json["starsAmenities"],
    starsValue: json["starsValue"],
    phone: !exists(json, "phone") ? undefined : json["phone"],
    twitter: !exists(json, "twitter") ? undefined : json["twitter"],
  };
}

export function VenueDetailDtoToJSON(value?: VenueDetailDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    venueId: value.venueId,
    venueName: value.venueName,
    url: value.url,
    thumbnail: value.thumbnail,
    excerpt: value.excerpt,
    tags: value.tags,
    address: value.address,
    starsBeer: value.starsBeer,
    starsAtmosphere: value.starsAtmosphere,
    starsAmenities: value.starsAmenities,
    starsValue: value.starsValue,
    phone: value.phone,
    twitter: value.twitter,
  };
}
