/* tslint:disable */
/* eslint-disable */
/**
 * Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VenueListItemDto
 */
export interface VenueListItemDto {
  /**
   *
   * @type {number}
   * @memberof VenueListItemDto
   */
  venueId: number;
  /**
   *
   * @type {string}
   * @memberof VenueListItemDto
   */
  venueName: string;
  /**
   *
   * @type {number}
   * @memberof VenueListItemDto
   */
  starsBeer: number;
  /**
   *
   * @type {number}
   * @memberof VenueListItemDto
   */
  starsAtmosphere: number;
  /**
   *
   * @type {number}
   * @memberof VenueListItemDto
   */
  starsAmenities: number;
  /**
   *
   * @type {number}
   * @memberof VenueListItemDto
   */
  starsValue: number;
  /**
   *
   * @type {number}
   * @memberof VenueListItemDto
   */
  distance: number;
}

/**
 * Check if a given object implements the VenueListItemDto interface.
 */
export function instanceOfVenueListItemDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "venueId" in value;
  isInstance = isInstance && "venueName" in value;
  isInstance = isInstance && "starsBeer" in value;
  isInstance = isInstance && "starsAtmosphere" in value;
  isInstance = isInstance && "starsAmenities" in value;
  isInstance = isInstance && "starsValue" in value;
  isInstance = isInstance && "distance" in value;

  return isInstance;
}

export function VenueListItemDtoFromJSON(json: any): VenueListItemDto {
  return VenueListItemDtoFromJSONTyped(json, false);
}

export function VenueListItemDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VenueListItemDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    venueId: json["venueId"],
    venueName: json["venueName"],
    starsBeer: json["starsBeer"],
    starsAtmosphere: json["starsAtmosphere"],
    starsAmenities: json["starsAmenities"],
    starsValue: json["starsValue"],
    distance: json["distance"],
  };
}

export function VenueListItemDtoToJSON(value?: VenueListItemDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    venueId: value.venueId,
    venueName: value.venueName,
    starsBeer: value.starsBeer,
    starsAtmosphere: value.starsAtmosphere,
    starsAmenities: value.starsAmenities,
    starsValue: value.starsValue,
    distance: value.distance,
  };
}
